version: 3

services:
    api:
        container_name: 'api-server'
        restart: always
        build:
            context: .
            target: $NODE_ENV
        command: node dist/index.js
        env_file: .env
        ports:
            - "3000:5000"
        depends_on:
            - database
        volumes:
            - uploads-persistence:./uploads
        networks:
            - app-network
    
    database:
        container_name: 'database'
        restart: always
        image: mysql:8.0.33
        ports:
            - "3306:3306"
        volumes:
            - database-persistence:/var/lib/mysql
        networks:
            - app-network

volumes:
    database-persistence:
    uploads-persistence:

networks:
    app-network:
        driver: bridge